service: ignitecertificate
frameworkVersion: '2'

plugins: 
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node14
    exclude: ['aws-sdk']
    define: 
      require.resolve: undefined
    platform: node
    concurrency: 10
    external: ['chrome-aws-lambda', 'dotenv']

  dotenv:
  path: ".env"

  dynamodb:
    stages: 
      - dev
      - local
    start: 
      port: 8000
      inMemory: true
      migrate: true

package:
  include: 
    - src/**
    - .env

provider: 
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:*
          Resource: "*"
        - Effect: Allow
          Action: 
            - s3:*
          Resource: "*"

functions: 
  generateCertificate:
    handler: src/functions/generateCertificate.handle
    events:
      - http: 
          path: /generateCertificate
          method: POST
          cors: true

  verifyCertificate:
    handler: src/functions/verifyCertificate.handle
    events: 
      - http: 
          path: /verifyCertificate/{id}
          method: GET
          cors: true

resources: 
  Resources: 
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: users_certificates
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH